export const Banks = [
  "Access Bank",
  "Citibank Nigeria",
  "Ecobank Nigeria",
  "Fidelity Bank",
  "First Bank of Nigeria",
  "First City Monument Bank (FCMB)",
  "Globus Bank",
  "Guaranty Trust Bank (GTBank)",
  "Heritage Bank",
  "Keystone Bank",
  "Polaris Bank",
  "PremiumTrust Bank",
  "Providus Bank",
  "Stanbic IBTC Bank",
  "Standard Chartered Bank Nigeria",
  "Sterling Bank",
  "SunTrust Bank",
  "Titan Trust Bank",
  "Union Bank of Nigeria",
  "United Bank for Africa (UBA)",
  "Unity Bank",
  "Wema Bank",
  "Zenith Bank",
  "Jaiz Bank",
  "TAJBank",
  "Lotus Bank",
  "Parallex Bank",
  "Opay (Olayemi Payment Service Bank)",
  "PalmPay (Payment Service Bank)",
  "Moniepoint Microfinance Bank",
  "Kuda Bank",
  "VFD Microfinance Bank",
  "Rubies Bank",
  "Sparkle Bank",
  "Eyowo Microfinance Bank",
  "9 Payment Service Bank",
  "Hope PSBank",
  "Heritage Bank Microfinance",
];
